### ISSUE TITLE
Is it updated for TOA yet? /Will it be updated for TOA? 

### ISSUE THREAD

**Issue by Lightningaus** [IlliaYalovoi/universal-checksum-patcher#10]
Is it updated for TOA yet? /Will it be updated for TOA?

**Comment by IlliaYalovoi** [comment]
Patcher is working on latest version of HoI4

**Comment by Lightningaus** [comment]
Has it been updated? (i dont mind if it isnt done, i am just checking) also would it be possible to make one for OS/X?
