### ISSUE TITLE
HOI4 1.15 Windows support broken 

### ISSUE THREAD

**Issue by eisstoss** [IlliaYalovoi/universal-checksum-patcher#14]
When the game is updated to 1.15, the patch is no longer supported. pls update,thanks

**Comment by IlliaYalovoi** [comment]
Still works for me. Try to reapply patch and write about results

**Comment by GamesWithNat** [comment]
Just booted up after repatching and doesnt work

**Comment by eisstoss** [comment]
It worked after trying again
