### ISSUE TITLE
error: file location not found

### ISSUE THREAD

**Issue by animasyon-kanali-official** [IlliaYalovoi/universal-checksum-patcher#9]
I tried it for hoi4 and it gave me this error, I tried again and it gave me again.
(my hoi4 is original)

**Comment by animasyon-kanali-official** [comment]
v Hearts of Iron IV
ERROR: cannot locate file in current directory

Press enter to exit

btw I'm using the latest version 1.13.6.7bda (c998) and it didn't work.

**Comment by IlliaYalovoi** [comment]
You should move patcher executable file (`universal-checksum-patcher.exe`) to game directory and run it from there. If you can't find game directory, you can right-click on game in Steam, then press `Manage` and in dropdown menu press `Browse local files`. Patcher trying to locate file with name `hoi4.exe`, so please look for it in this directory

**Comment by animasyon-kanali-official** [comment]
thank you it worked.
I think it would be better if you write in more detail on readme.
